bf16: true
dataset_kwargs:
  add_special_tokens: false
  append_concat_token: false
dataset_mixer:
  /home/test/test04/yuanjiarui/project/src/my_datasets/hotpot_qa_sft_v3/iteration_0: 1.0
dataset_splits:
- train
- test
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
model_name_or_path: /home/test/testdata/models/Meta-Llama-3-8B-Instruct
model_revision: main
num_train_epochs: 2
output_dir: /home/test/test04/yuanjiarui/project/checkpoints/hotpot_qa_sft_v3/iteration_0
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
preprocessing_num_workers: 8
push_to_hub: false
remove_unused_columns: true
save_strategy: 'no'
seed: 42
tokenizer_name_or_path: /home/test/test04/yuanjiarui/project/checkpoints/sft_llama_8b_cleaned_format10k
torch_dtype: bfloat16
use_flash_attention_2: true
warmup_ratio: 0.1
