bf16: true
dataset_kwargs:
  add_special_tokens: false
  append_concat_token: false
dataset_mixer:
  /home/test/test04/yuanjiarui/project/src/my_datasets/arc_sft_v3/modify: 1.0
dataset_splits:
- train
- test
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
model_name_or_path: /home/test/testdata/models/Meta-Llama-3-8B-Instruct
model_revision: main
num_train_epochs: 4
output_dir: /home/test/test04/yuanjiarui/project/checkpoints/arc_modify/lr_1e-06_epoch_4_batch_2
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
preprocessing_num_workers: 8
push_to_hub: false
remove_unused_columns: true
save_strategy: 'no'
seed: 42
tokenizer_name_or_path: /home/test/testdata/models/Meta-Llama-3-8B-Instruct
torch_dtype: bfloat16
use_flash_attention_2: true
warmup_ratio: 0.1
